name: Build
on:
  push:
    branches:
      - test-workflow-on-fork

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npx honkit build
